### ISSUE TITLE
Not sure /applications endpoint works as expected

### ISSUE THREAD

**Issue by skandragon** [homedepot/go-clouddriver#124]
It looks like the database contains `kind` strings like `Deployment`, but the query looks for `deployment` in the `sql/client.go` `ListKubernetesClustersByFields`:

```go
	db := c.db.Select(list).Where("kind in ('deployment', 'statefulSet', 'replicaSet', 'ingress', 'service', 'daemonSet')").Group(list).Find(&rs)
```

Looking at the sqllite database:

```
sqlite> select kind from kubernetes_resources;
Service
Deployment
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
ReplicaSet
```

**Comment by skandragon** [comment]
@billiford I'm experimenting with the go implementation of Clouddriver, and would also love to chat about if this is currently used, and if so, how things like application refreshing and such is performed at Home Depot.

**Comment by billiford** [comment]
The `in` operator for our SQL DB is case-insensitive. We use MySQL and haven't seen any issues with this for application refreshing.
```
MySQL [clouddriver]> select kind from kubernetes_resources where kind in ('replicaSet');
+------------+
| kind       |
+------------+
| ReplicaSet |
| ReplicaSet |
| ReplicaSet |
+------------+
3 rows in set (0.002 sec)
```

**Comment by billiford** [comment]
You can contact me via email and send me your work email(s). I'd be happy to set up meeting.

**Comment by skandragon** [comment]
Ahh, the fallback to SQLLite I was using during testing is not case insensitive...  I have reached out to you via my flame.org address, but no reply yet.  Perhaps I was caught as spam?  In any case, I'll mail from opsmx.com or opsmx.io, whatever my mail is these days.  :)
