### ISSUE TITLE
making Go Clouddriver extensible

### ISSUE THREAD

**Issue by billiford** [homedepot/go-clouddriver#51]
**Problem Statement**

Go Clouddriver is currently very tied to a Kubernetes implementation, especially the `/applications/*` endpoints. We need to make Providers generic, so that all providers implement some global `Provider` interface and we can get Server Groups for the Clusters page regardless of what the provider's *type* is.

**Goal**

To support more than just Kubernetes providers.

**Current Solution**

I have created the following `Provider` interface at `pkg/provider.go`. This is not pushed to a branch currently.
```go
package clouddriver

// Provider describes some kind of service account
// that has the ability to get server groups,
// server group managers, and load balancers.
type Provider interface {
	Instance(SearchOptions) (Instance, error)
	LoadBalancers(SearchOptions) ([]LoadBalancer, error)
	ServerGroup(SearchOptions) (ServerGroup, error)
	ServerGroups(SearchOptions) ([]ServerGroup, error)
	ServerGroupManagers(SearchOptions) ([]ServerGroupManager, error)
}

type SearchOptions struct {
	Application string
	Location    string
	Kind        string
	Name        string
}
```
This idea is to have any type of Provider (Kubernetes, AppEngine, Cloud Foundry, etc) implement this interface so that whenever we call `provider.ServerGroups()` from the `applications.go` file, it will return some generic `ServerGroup` type regardless of which type of provider is making the call. This has the added benefit of segregating logic to its own package.

**Problem: where/how to handle setting up these providers?**

This brings us to our main problem - how to handle setting up these providers in a *generic* way that includes *authentication*.

Let's take a look at a snippet of code for when we set up a Kubernetes provider instance. You can find this snippet littered throughout the project.
```go
        // Get the kubernetes provider from the DB.
	provider, err := sqlClient.GetKubernetesProvider(account)
	if err != nil {
		return config, http.StatusBadRequest, err
	}
        // Get the auth token for the provider.
	token, err := arcadeClient.Token(provider.TokenProvider)
	if err != nil {
		return config, http.StatusInternalServerError, err
	}
        // Get the CA Data for the Kubernetes config.
	caData, err := base64.StdEncoding.DecodeString(provider.CAData)
	if err != nil {
		return config, http.StatusBadRequest, err
	}
        // Declare a rest config.k
	config = &rest.Config{
		Host:        provider.Host,
		BearerToken: token,
		TLSClientConfig: rest.TLSClientConfig{
			CAData: caData,
		},
	}
	// Declare a kube client from this config.
	kubeClient, err := kubeController.NewClient(config)
	if err != nil {
		clouddriver.Error(c, http.StatusInternalServerError, err)
		return
	}
```
As we can see this is all **not** generic and is associated with setting up a Kubernetes provider.

Instead, It would be nice to see something like this:
```go
        // Get the provider from the DB that has already had its authentication and clients setup.
        provider, err := sqlClient.GetProvider(account)
        if err != nil {
                // do something
        }
        // Get server groups.
       sg, err := provider.ServerGroups(...)
       // do stuff
```
This is much cleaner, but presents us with a couple of problems. Where do we set up the client configs and get the auth token from arcade?

I thought about one way to handle this is to drop the `kubernetes.Controller` and instead use a generic `clouddriver.Controller` which looks something like:
```go
package clouddriver

type Controller struct {
  ac arcade.Client
}

func (c *Controller) NewKubernetesProvider(...) (kubernetes.Provider, error) {
  // logic here to set up rest config and get the token from Arcade
}

func (c *Controller) NewAppEngineProvider(...) (appengine.Provider, error) {
  // logic here to set up the new appengine provider.
}
```
It might be possible to just have it implement `NewProvider(...)`, but you get the idea: create a generic controller that holds an instance of Arcade whose purpose is to generate providers.

But where do we call this generic controller?

One thought is to integrate it into the SQL Client:
```go
type sqlClient struct {
	db *gorm.DB
	cc clouddriver.Controller
}
```
And then call the `NewProvider` func whenever providers are requested from the DB. Something about this feels weird - tying generating clients and authentication tokens to a SQL client. Is this bad practice? Is there a better way to architect this?

**Comment by dmrogers7** [comment]
I think the entry point of getting a provider should be the controller and it should do the work of retrieving it from the database and configuring the credentials.  Rather than having the SQL client hold a reference to the controller, the `clouddriver.Controller` should hold a reference to the SQL client.

```go
package clouddriver

type Controller struct {
  ac arcade.Client
  sc sql.Client
}

func (c *Controller) NewKubernetesProvider(...) (kubernetes.Provider, error) {
    // Get the kubernetes provider from the DB.
    provider, err := sc.GetKubernetesProvider(account)
    if err != nil {
      return nil, err
    }
    // logic here to set up rest config and get the token from Arcade
}

func (c *Controller) NewAppEngineProvider(...) (appengine.Provider, error) {
    // Get the appengine provider from the DB.
    provider, err := sc.GetAppEngineProvider(account)
    if err != nil {
      return nil, err
    }
    // logic here to set up the new appengine provider.
}
```

**Comment by billiford** [comment]
It makes sense to pass the ownership of the SQL client to the controller instead of having the sql client own the controller. Thanks for the input!
