### ISSUE TITLE
Test suite doesn't pass with go version [go1.16.6 darwin/amd64]

### ISSUE THREAD

**Issue by npmaile** [homedepot/go-clouddriver#60]
I upgraded to the newest go version(1.16.6), and `ginkgo ./...` fails in package go-clouddriver/pkg/http/core
I looked into it a little and it appears that the httptest package exhausts available resources to open the test servers when opening so many of them concurrently. =

**Comment by billiford** [comment]
What's the error being thrown?

**Comment by billiford** [comment]
I'm guessing it's the error
```
  Test Panicked
  httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: too many open files
```
This can be fixed by increasing your `ulimit` on OSX.
